### ISSUE TITLE
`lib/hex/scm.ex:85: Hex.SCM.checkout/1` error

### ISSUE THREAD

**Issue by OvermindDL1** [hexpm/hex#247]
Was asked by @ericmj from https://elixirforum.com/t/error-compiling-erlang-package-with-rebar/981/9 to report this bug that I ran across while I was messing around.

To reproduce:
```bash
$ mkdir ./testing_crash

$ cd ./testing_crash

$ cat mix.exs # I've reduced this to there being no other files in this directory
defmodule TestingCrash.Mixfile do
  use Mix.Project

  def project do
    [app: :testing_crash,
     version: "0.1.0",
     elixir: "~> 1.3",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:poolboy, "~> 0.8.1-p3", [hex: :basho_poolboy, manager: :rebar3]},
      {:riak_core, "~> 2.2", [hex: :riak_core_ng, manager: :rebar3]}
    ]
  end
end

$ mix deps.get
Running dependency resolution
Dependency resolution completed
  basho_poolboy: 0.8.1-p3
  basho_stats: 1.0.3
  bear: 0.8.3
  chash: 0.1.1
  clique: 3.0.1
  cuttlefish: 2.0.7
  edown: 0.7.0
  eleveldb: 2.1.3
  erocksdb: 0.4.0
  exometer_core: 1.0.0
  folsom: 0.8.3
  getopt: 0.8.2
  goldrush: 0.1.7
  lager: 3.0.2
  parse_trans: 2.9.0
  pbkdf2: 2.0.0
  riak_core_ng: 2.2.0
  riak_ensemble: 2.1.3
  riak_sysmon: 2.1.2
  setup: 1.7.0
* Getting poolboy (Hex package)
  Checking package (https://repo.hex.pm/tarballs/basho_poolboy-0.8.1-p3.tar)
  Using locally cached package
* Getting riak_core (Hex package)
  Checking package (https://repo.hex.pm/tarballs/riak_core_ng-2.2.0.tar)
  Using locally cached package
* Getting riak_sysmon (Hex package)
  Checking package (https://repo.hex.pm/tarballs/riak_sysmon-2.1.2.tar)
  Using locally cached package
* Getting riak_ensemble (Hex package)
  Checking package (https://repo.hex.pm/tarballs/riak_ensemble-2.1.3.tar)
  Using locally cached package
* Getting pbkdf2 (Hex package)
  Checking package (https://repo.hex.pm/tarballs/pbkdf2-2.0.0.tar)
  Using locally cached package
* Getting lager (Hex package)
  Checking package (https://repo.hex.pm/tarballs/lager-3.0.2.tar)
  Using locally cached package
* Getting goldrush (Hex package)
  Checking package (https://repo.hex.pm/tarballs/goldrush-0.1.7.tar)
  Using locally cached package
* Getting exometer_core (Hex package)
  Checking package (https://repo.hex.pm/tarballs/exometer_core-1.0.0.tar)
  Using locally cached package
* Getting erocksdb (Hex package)
  Checking package (https://repo.hex.pm/tarballs/erocksdb-0.4.0.tar)
  Using locally cached package
* Getting eleveldb (Hex package)
  Checking package (https://repo.hex.pm/tarballs/eleveldb-2.1.3.tar)
  Using locally cached package
* Getting edown (Hex package)
  Checking package (https://repo.hex.pm/tarballs/edown-0.7.0.tar)
  Using locally cached package
* Getting cuttlefish (Hex package)
  Checking package (https://repo.hex.pm/tarballs/cuttlefish-2.0.7.tar)
  Using locally cached package
* Getting clique (Hex package)
  Checking package (https://repo.hex.pm/tarballs/clique-3.0.1.tar)
  Using locally cached package
* Getting chash (Hex package)
  Checking package (https://repo.hex.pm/tarballs/chash-0.1.1.tar)
  Using locally cached package
* Getting basho_stats (Hex package)
  Checking package (https://repo.hex.pm/tarballs/basho_stats-1.0.3.tar)
  Using locally cached package
* Getting basho_poolboy (Hex package)
** (MatchError) no match of right hand side value: nil
    (hex) lib/hex/scm.ex:85: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:174: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:183: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:114: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:99: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3


$ mix hex.info
Hex:    0.12.1
Elixir: 1.3.1
OTP:    18.3

Built with: Elixir 1.2.5 and OTP 18.3.3

Registry file available (last updated: 2016-07-01 11:24:40)
File size:   2321kB (compressed 758kb)
Memory size: 6227kB
Fetch time:  1500ms
Load time:   31ms
Packages #:  2314
Versions #:  10570
```

So in other words make an empty directory, put this into mix.exs:
```elixir
defmodule TestingCrash.Mixfile do
  use Mix.Project

  def project do
    [app: :testing_crash,
     version: "0.1.0",
     elixir: "~> 1.3",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:poolboy, "~> 0.8.1-p3", [hex: :basho_poolboy, manager: :rebar3]},
      {:riak_core, "~> 2.2", [hex: :riak_core_ng, manager: :rebar3]}
    ]
  end
end
```
Then run `mix deps.get`.  Happens every time for me, new directories, full directories, empty directories other than the mix.exs file, etc....  The dependencies lines were copied from the above linked forum thread.

**Comment by OvermindDL1** [comment]
Oh, and for note, `mix deps.get` never creates the mix.lock file before it crashes, only a deps directory with the deps that it could get.

**Comment by ericmj** [comment]
The error is that the package `riak_core_ng` has set the wrong application name for the `basho_poolboy` dependency.
