### ISSUE TITLE
can't figure out 'Could not start Hex.' on heroku

### ISSUE THREAD

**Issue by joshcrews** [hexpm/hex#366]
This app has been running on heroku (under active development) since January 2016.   I have two other (younger) heroku elixir/phoenix apps that are not experiencing this problem

```
git push staging master -f         
Counting objects: 162, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (161/161), done.
Writing objects: 100% (162/162), 23.14 KiB | 0 bytes/s, done.
Total 162 (delta 123), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Elixir app detected
remote: -----> Checking Erlang and Elixir versions
remote:        Will use the following versions:
remote:        * Stack cedar-14
remote:        * Erlang 19.1
remote:        * Elixir 1.4.0 
remote: -----> Will export the following config vars:
remote: DATABASE_URL
remote: FROM_ADDRESS
remote: HEROKU_POSTGRESQL_AMBER_URL
remote: HEROKU_POSTGRESQL_GOLD_URL
remote: HEX_MIRROR
remote: HONEYBADGER_API_KEY
remote: LEGACY_DATABASE_URL
remote: LOLO_API_KEY
remote: LOLO_DOMAIN
remote: MAILGUN_DOMAIN
remote: MIX_ENV
remote: SECRET_KEY_BASE
remote: SENDGRID_PASSWORD
remote: SENDGRID_USERNAME
remote: SHARED_SECRET
remote:        * MIX_ENV=staging
remote: -----> Cleaning all cache to force rebuilds
remote: -----> Fetching Erlang 19.1
remote: -----> Installing Erlang 19.1 (changed)
remote: 
remote: -----> Fetching Elixir v1.4.0
remote: -----> Installing Elixir v1.4.0 (changed)
remote: -----> Installing Hex
remote: * creating /app/.mix/archives/hex-0.16.0
remote: -----> Installing rebar
remote: * creating /app/.mix/rebar
remote: * creating /app/.mix/rebar3
remote: -----> Fetching app dependencies with mix
remote: warning: variable "aliases" does not exist and is being expanded to "aliases()", please use parentheses to remove the ambiguity or change the variable name
remote:   mix.exs:12
remote: 
remote: warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
remote:   mix.exs:13
remote: 
remote: Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
remote: 
remote: 03:13:16.009 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
remote:     ** (EXIT) an exception was raised:
remote:         ** (Mix.Error) The environment variable HEX_MIRROR and configuration key mirror_url have been deprecated in favor of setting the repository configuration through the `mix hex.repo` task
remote:             (mix) lib/mix.ex:276: Mix.raise/1
remote:             (hex) lib/hex/state.ex:17: Hex.State.init/1
remote:             (elixir) lib/agent/server.ex:8: Agent.Server.init/1
remote:             (stdlib) gen_server.erl:328: :gen_server.init_it/6
remote:             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
remote: 
remote: 03:13:16.010 [info]  Application inets exited: :stopped
remote: 
remote: 03:13:16.010 [info]  Application ssl exited: :stopped
remote: 
remote: 03:13:16.010 [info]  Application public_key exited: :stopped
remote: 
remote: 03:13:16.011 [info]  Application asn1 exited: :stopped
remote: 
remote: 03:13:16.011 [info]  Application crypto exited: :stopped
remote: ** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {%Mix.Error{message: "The environment variable HEX_MIRROR and configuration key mirror_url have been deprecated in favor of setting the repository configuration through the `mix hex.repo` task", mix: true}, [{Mix, :raise, 1, [file: 'lib/mix.ex', line: 276]}, {Hex.State, :init, 1, [file: 'lib/hex/state.ex', line: 17]}, {Agent.Server, :init, 1, [file: 'lib/agent/server.ex', line: 8]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}, {Hex, :start, [:normal, []]}}}}
remote:     (hex) lib/hex.ex:5: Hex.start/0
remote:     (mix) lib/mix/hex.ex:53: Mix.Hex.start/0
remote:     (mix) lib/mix/dep/loader.ex:144: Mix.Dep.Loader.with_scm_and_app/4
remote:     (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
remote:     (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
remote:     (mix) lib/mix/dep/loader.ex:299: Mix.Dep.Loader.mix_children/1
remote:     (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
remote:     (mix) lib/mix/dep/converger.ex:56: Mix.Dep.Converger.all/4
remote: 
remote:  !     Push rejected, failed to compile Elixir app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !	Push rejected to thanklocal-staging.
remote: 
To https://git.heroku.com/thanklocal-staging.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/thanklocal-staging.git'
```

my buildpacks
```
heroku buildpacks -r staging
=== thanklocal-staging Buildpack URLs
1. https://github.com/hashnuke/heroku-buildpack-elixir
2. https://github.com/gjaldon/phoenix-static-buildpack
```

**Comment by ericmj** [comment]
It looks like you have `HEX_MIRROR` set in your Heroku config. Do you need this configuration? If so you need to set it with the new `mix hex.repo` tasks.

**Comment by joshcrews** [comment]
That was it!
Thank you.
I can't remember why I did it.  I found the value I had put: 
HEX_MIRROR:                  https://s3.amazonaws.com/s3.hex.pm
For anyone else, you can remove that heroku env variable with `heroku config:remove HEX_MIRROR`
