### ISSUE TITLE
Function clause error on invalid requirement

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#447]
When I defined an invalid requirement in my deps:

```elixir
{:ex_doc, "= 0.17.0"}
```

I got a function clause error:

```
$ mix deps.get
** (FunctionClauseError) no function clause matching in Version.InvalidRequirementError.exception/1

    The following arguments were given to Version.InvalidRequirementError.exception/1:

        # 1
        [message: "= 0.17.0"]

    Attempted function clauses (showing 1 out of 1):

        def exception(requirement) when is_binary(requirement)

    (elixir) lib/version.ex:109: Version.InvalidRequirementError.exception/1
    (hex) lib/hex/version.ex:97: Hex.Version.parse_requirement!/2
    (hex) lib/hex/version.ex:23: anonymous fn/3 in Hex.Version.match?/3
    (hex) lib/hex/version.ex:106: Hex.Version.cache/2
    (hex) lib/hex/remote_converger.ex:330: anonymous fn/2 in Hex.RemoteConverger.unlock_deps/2
    (elixir) lib/enum.ex:2854: Enum.filter_list/2
    (hex) lib/hex/remote_converger.ex:325: Hex.RemoteConverger.unlock_deps/2
    (hex) lib/hex/remote_converger.ex:313: Hex.RemoteConverger.prepare_locked/3
```

Some info:

```
$ mix hex.info
Hex:    0.16.1
Elixir: 1.6.0-dev
OTP:    20.0

Built with: Elixir 1.4.5 and OTP 18.3
```

It is likely broken because of this commit: https://github.com/elixir-lang/elixir/commit/824b26842052fc9f92a1916995ee91d5ef1c86e8#diff-32f7cb190f9e0e7f5bdd6326d7aad69d

**Comment by wojtekmach** [comment]
This is fixed in 0.17, please upgrade!

**Comment by josevalim** [comment]
*on the tune of take on me*

Shaaaaaaaaame ooonnnnnn meeeeeee
(shame on me)
Shaaaaaaaaame meeeeeee ooooooon
(shame on me)
I'll upgraaaaaaade
In a day or twooooooooooooo

**Comment by wojtekmach** [comment]
shame on me for the regression 🙊 have a good weekend!
