### ISSUE TITLE
HEX_MIRROR not work?

### ISSUE THREAD

**Issue by zw0** [hexpm/hex#456]
docker build log 

```
Sending build context to Docker daemon  4.346MB
Step 1/9 : FROM bitwalker/alpine-elixir:1.5.2
 ---> 8d1aa3be4c12
Step 2/9 : EXPOSE 3001
 ---> Running in fdb6252ec101
 ---> a06b45b11e60
Removing intermediate container fdb6252ec101
Step 3/9 : ENV MIX_ENV prod
 ---> Running in 49a1ed118b22
 ---> cf201dc4ee32
Removing intermediate container 49a1ed118b22
Step 4/9 : ADD mix.* ./
 ---> cf943691e5cf
Step 5/9 : RUN HEX_MIRROR=https://cdn.jsdelivr.net/hex  mix do hex.config, deps.get
 ---> Running in c26353e61a65
Resolving Hex dependencies...
Dependency resolution completed:
  certifi 2.0.0
  distillery 1.5.2
  hackney 1.10.1
  idna 5.1.0
  metrics 1.0.1
  mimerl 1.0.2
  poison 3.1.0
  sentry 6.0.3
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.3.1
  uuid 1.1.8
* Getting poison (Hex package)
  Checking package (https://repo.hex.pm/tarballs/poison-3.1.0.tar)
Request failed (:timeout)
** (Mix) Package fetch failed and no cached copy available
The command '/bin/sh -c HEX_MIRROR=https://cdn.jsdelivr.net/hex  mix do hex.config, deps.get' returned a non-zero code: 1
```

`Step 5/9 : RUN HEX_MIRROR=https://cdn.jsdelivr.net/hex  mix do hex.config, deps.ge`
This set `HEX_MIRROR` but hex not work 

```
  Checking package (https://repo.hex.pm/tarballs/poison-3.1.0.tar)
Request failed (:timeout)
```

my dockerfile   config 

```
ADD mix.* ./
RUN HEX_MIRROR=https://cdn.jsdelivr.net/hex  mix do  deps.get
```
or 

```
RUN mix hex.config mirror_url https://hexpm.upyun.com 
RUN mix hex.config
```

**Comment by zw0** [comment]
and 

```
Step 5/9 : RUN HEX_MIRROR=https://hexpm.upyun.com  mix deps.get
 ---> Running in aacd27e2a7c7
Failed to fetch record for 'hexpm/hackney' from registry (using cache)
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "hackney"}, 60000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
            (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :timeout})
            (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
            (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
            (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
            (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    (hex) lib/hex/remote_converger.ex:261: Hex.RemoteConverger.check_dep/3
    (elixir) lib/enum.ex:681: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1843: Enum.each/2
    (hex) lib/hex/remote_converger.ex:39: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:94: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4

07:07:09.865 [error] GenServer Hex.Registry.Server terminating
** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
    (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :timeout})
    (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
    (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:get_package, "hexpm", "hackney", {:error, :timeout}}
State: %{closing_fun: nil, ets: #Reference<0.2281920295.731774977.141133>, fetched: #MapSet<[{"hexpm", "certifi"}, {"hexpm", "distillery"}, {"hexpm", "idna"}, {"hexpm", "metrics"}, {"hexpm", "mimerl"}, {"hexpm", "poison"}, {"hexpm", "sentry"}, {"hexpm", "ssl_verify_fun"}, {"hexpm", "unicode_util_compat"}, {"hexpm", "uuid"}]>, offline?: false, path: "/opt/app/.hex/cache.ets", pending: #MapSet<[{"hexpm", "hackney"}]>, waiting: %{{"hexpm", "hackney"} => [{{#PID<0.74.0>, #Reference<0.2281920295.731643908.141836>}, #Function<3.75490635/0 in Hex.Registry.Server.handle_call/3>}]}}
The command '/bin/sh -c HEX_MIRROR=https://hexpm.upyun.com  mix deps.get' returned a non-zero code: 1
~/j/omsentry |master⚡*? ❯❯❯

```

**Comment by ericmj** [comment]
This bug should be fixed in master.

**Comment by zw0** [comment]
how to use master hex? 

my hex version 

```
Hex:    0.17.1
Elixir: 1.5.2
OTP:    20.1
```

**Comment by ericmj** [comment]
Clone this repository and run `mix install` in it.
