### ISSUE TITLE
MatchError when setting up Hex for the first time

### ISSUE THREAD

**Issue by whatyouhide** [hexpm/hex#520]
Was setting up Hex on a new machine for publishing and when authenticating, I inserted username, password, local pw, and local pw confirmation, and I got this:

```
No authenticated user found. Do you want to authenticate now? [Yn] Y
Username: whatyouhide
Account password:
Generating API key...
You have authenticated on Hex using your account password. However, Hex requires you to have a local password that applies only to this machine for security purposes. Please enter it.
Local password:
Local password (confirm):
Generating organization keys...
** (MatchError) no match of right hand side value: :error
    (hex) lib/hex/crypto/encryption.ex:30: Hex.Crypto.Encryption.decrypt/2
    (hex) lib/mix/tasks/hex.ex:161: Mix.Tasks.Hex.auth_info/0
    (hex) lib/mix/tasks/hex.publish.ex:149: Mix.Tasks.Hex.Publish.create/3
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

I like to think I got the passwords all right but maybe I didn't, in that case the error is a bit cryptic though :P 

Elixir: master
Hex: v0.17.3

**Comment by kipcole9** [comment]
I think this may be the same as [#516](https://github.com/hexpm/hex/issues/516)

**Comment by whatyouhide** [comment]
Ah the good old quick issue without looking at other issues, one of my favourite open source things! :D Sorry Hex folks!
