### ISSUE TITLE
Unit tests fail on Windows

### ISSUE THREAD

**Issue by TroyLaurin** [hexpm/hex#525]
It comes down to matching against the output of `IO.ANSI.format`.
Sample errors:

```
  1) test pre-release message (Hex.ResolverTest)
     test/hex/resolver_test.exs:243
     Assertion with == failed
     code:  assert resolve(deps) == "\e[4mFailed to use \"beta\" because there are no packages that matches the requirement\e[0m\n  \e[1mmix.exs\e[0m specifies \e[31m~> 1.0 and > 1.0.0\e[0m *\n\e[0m\n* This requirement does not match pre-releases. To match pre-releases include a pre-release in the requirement, such as: \"~> 2.0-beta\".\n\n"
     left:  "Failed to use \"beta\" because there are no packages that matches the requirement\n  mix.exs specifies ~> 1.0 and > 1.0.0 *\n\n* This requirement does not match pre-releases. To match pre-releases include a pre-release in the requirement, such as: \"~> 2.0-beta\".\n\n"
     right: "\e[4mFailed to use \"beta\" because there are no packages that matches the requirement\e[0m\n  \e[1mmix.exs\e[0m specifies \e[31m~> 1.0 and > 1.0.0\e[0m *\n\e[0m\n* This requirement does not match pre-releases. To match pre-releases include a pre-release in the requirement, such as: \"~> 2.0-beta\".\n\n"
     stacktrace:
       test/hex/resolver_test.exs:246: (test)



  2) test simple (Hex.ResolverTest)
     test/hex/resolver_test.exs:57
     Assertion with == failed
     code:  assert resolve(deps) == "\e[4mFailed to use \"foo\" because there are no packages that matches the requirement\e[0m\n  \e[1mmix.exs\e[0m specifies \e[31m~> 0.3.0\e[0m\n\e[0m\n"
     left:  "Failed to use \"foo\" because there are no packages that matches the requirement\n  mix.exs specifies ~> 0.3.0\n\n"
     right: "\e[4mFailed to use \"foo\" because there are no packages that matches the requirement\e[0m\n  \e[1mmix.exs\e[0m specifies \e[31m~> 0.3.0\e[0m\n\e[0m\n"
     stacktrace:
       test/hex/resolver_test.exs:69: (test)
```

As a workaround, the following line can be added to `config/config.exs`, in the test section:
```
  Application.put_env(:elixir, :ansi_enabled, true)
```

It makes the output look bad if run in a command terminal, but it works fine in an MSYS terminal.

A more robust fix would be to change the assertions to match against regular expressions for the error messages, to skip over the (possibly validly missing) ANSI codes.

**Comment by TroyLaurin** [comment]
Some tests fixed in https://github.com/hexpm/hex/pull/526

All of the non-integration tests pass, though there are still 9 failing integration tests:

```
$ mix test
Compiling 1 file (.ex)
Excluding tags: [:skip]

....................................

  1) test deps.update locked dependency (Hex.MixTaskTest)
     test/hex/mix_task_test.exs:321
     No message matching {:mix_shell, :info, ["\e[32m  ecto 0.2.1\e[0m"]} after 0ms.
     Process mailbox:
       {:mix_shell, :info, ["Resolving Hex dependencies..."]}
       {:mix_shell, :info, ["Dependency resolution completed:"]}
       {:mix_shell, :info, ["  ecto 0.2.1"]}
       {:mix_shell, :info, ["  ex_doc 0.1.0"]}
       {:mix_shell, :info, ["  postgrex 0.2.1"]}
       {:mix_shell, :info, ["* Getting ecto (Hex package)"]}
       {:mix_shell, :info, ["* Getting ex_doc (Hex package)"]}
       {:mix_shell, :info, ["* Getting postgrex (Hex package)"]}
     stacktrace:
       test/hex/mix_task_test.exs:330: anonymous fn/0 in Hex.MixTaskTest."test deps.update locked dependency"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/hex/mix_task_test.exs:324: (test)

.............

  2) test create with metadata (Mix.Tasks.Hex.PublishTest)
     test/mix/tasks/hex.publish_test.exs:240
     No message matching {:mix_shell, :info, [^message]} after 0ms.
     The following variables were pinned:
       message = "Publishing package to \e[1mpublic\e[0m repository hexpm."
     Process mailbox:
       {:mix_shell, :info, ["  App: release_c"]}
       {:mix_shell, :info, ["  Name: release_c"]}
       {:mix_shell, :info, ["    missing.txt"]}
       {:mix_shell, :info, ["    missing/file.txt"]}
       {:mix_shell, :info, ["  Description: foo"]}
       {:mix_shell, :info, ["  Version: 0.0.3"]}
       {:mix_shell, :info, ["  Build tools: mix"]}
       {:mix_shell, :info, ["  Licenses: Apache"]}
       {:mix_shell, :info, ["  Maintainers: maintainers"]}
       {:mix_shell, :info, ["  Links: \n    a: http://a"]}
     Showing only 10 of 16 messages.
     code: in_tmp(fn ->
     stacktrace:
       test/mix/tasks/hex.publish_test.exs:262: anonymous fn/0 in Mix.Tasks.Hex.PublishTest."test create with metadata"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.publish_test.exs:243: (test)

...

  3) test create package with :organization config (Mix.Tasks.Hex.PublishTest)
     test/mix/tasks/hex.publish_test.exs:270
     ** (File.Error) could not make directory (with -p) "c:/Work/TSR/hex/tmp/Elixir.Mix.Tasks.Hex.PublishTest/test create package with :organization config": I/O error
     code: in_tmp(fn ->
     stacktrace:
       (elixir) lib/file.ex:271: File.mkdir_p!/1
       test/support/case.ex:55: HexTest.Case.in_tmp/2
       test/mix/tasks/hex.publish_test.exs:273: (test)

.

  4) test create package with :organization config with no organization in user config (Mix.Tasks.Hex.PublishTest)
     test/mix/tasks/hex.publish_test.exs:291
     ** (File.Error) could not make directory (with -p) "c:/Work/TSR/hex/tmp/Elixir.Mix.Tasks.Hex.PublishTest/test create package with :organization config with no organization in user config": I/O error
     code: in_tmp(fn ->
     stacktrace:
       (elixir) lib/file.ex:271: File.mkdir_p!/1
       test/support/case.ex:55: HexTest.Case.in_tmp/2
       test/mix/tasks/hex.publish_test.exs:294: (test)

.....

  5) test create package with --organization flag overrides :organization config (Mix.Tasks.Hex.PublishTest)
     test/mix/tasks/hex.publish_test.exs:306
     ** (File.Error) could not make directory (with -p) "c:/Work/TSR/hex/tmp/Elixir.Mix.Tasks.Hex.PublishTest/test create package with --organization flag overrides :organization config": I/O error
     code: in_tmp(fn ->
     stacktrace:
       (elixir) lib/file.ex:271: File.mkdir_p!/1
       test/support/case.ex:55: HexTest.Case.in_tmp/2
       test/mix/tasks/hex.publish_test.exs:309: (test)

..........................

  6) test search (Mix.Tasks.Hex.SearchTest)
     test/mix/tasks/hex.search_test.exs:5
     No message matching {:mix_shell, :info, ["ex_doc\e[0m" <> ex_doc]} after 0ms.
     Process mailbox:
       {:mix_shell, :info, ["Package       Description       Version  URL                                          "]}
       {:mix_shell, :info, ["only_doc      Some description  0.1.0    http://localhost:4043/packages/only_doc      "]}
       {:mix_shell, :info, ["ex_doc        Some description  0.1.0    http://localhost:4043/packages/ex_doc        "]}
       {:mix_shell, :info, ["docs_package  empty             1.1.2    http://localhost:4043/packages/docs_package  "]}
     code: assert_received {:mix_shell, :info, ["ex_doc\e[0m" <> ex_doc]}
     stacktrace:
       test/mix/tasks/hex.search_test.exs:7: (test)

.

  7) test search with authenticated user (Mix.Tasks.Hex.SearchTest)
     test/mix/tasks/hex.search_test.exs:22
     No message matching {:mix_shell, :info, ["ex_doc\e[0m" <> ex_doc]} after 0ms.
     Process mailbox:
       {:mix_shell_input, :yes?, false}
       {:mix_shell, :prompt, ["Local password: "]}
       {:mix_shell, :info, ["Package       Description       Version  URL                                          "]}
       {:mix_shell, :info, ["only_doc      Some description  0.1.0    http://localhost:4043/packages/only_doc      "]}
       {:mix_shell, :info, ["ex_doc        Some description  0.1.0    http://localhost:4043/packages/ex_doc        "]}
       {:mix_shell, :info, ["docs_package  empty             1.1.2    http://localhost:4043/packages/docs_package  "]}
     code: in_tmp(fn ->
     stacktrace:
       test/mix/tasks/hex.search_test.exs:32: anonymous fn/0 in Mix.Tasks.Hex.SearchTest."test search with authenticated user"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.search_test.exs:23: (test)

.........

  8) test create with excluded files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:84
     Assertion with == failed
     code:  assert File.stat!("unzip/myfile.txt").mode() == 33188
     left:  33206
     right: 33188
     stacktrace:
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:87: (test)

.......

  9) test create with files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:41
     Assertion with != failed, both sides are exactly equal
     code: assert File.stat!("unzip/empty_dir").mtime() != mtime_empty_dir
     left: {{2018, 3, 13}, {13, 34, 41}}
     stacktrace:
       test/mix/tasks/hex.build_test.exs:69: anonymous fn/0 in Mix.Tasks.Hex.BuildTest."test create with files"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:44: (test)

..............................................................

Finished in 12.2 seconds
2 properties, 177 tests, 9 failures, 7 skipped

Randomized with seed 43000
```

For 1 and 2, I'm not sure how to match the message that may or may not contain an ANSI sequence.
For 3, 4, and 5, the I/O error is likely to be Windows complaining about a filename containing a colon.
6 and 7 could be worked around by simply not including the ANSI code in the string match, and allowing it to be caught in the `ex_doc` capture... with the caveat that will match *any* package with a name prefix of "ex_doc"... which may or may not be acceptable.
8 and 9 are relying on Windows to do the expected thing with mtimes and file properties.  I'm not sure how likely that is to work, or how dependent on Windows version or filesystem that might end up being.

**Comment by ericmj** [comment]
@TroyLaurin Which tests are still failing on Windows?

**Comment by TroyLaurin** [comment]
Just updated from master:

```
Excluding tags: [:skip]

...............................................................................................................

  1) test create with excluded files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:86
     Assertion with == failed
     code:  assert File.stat!("unzip/myfile.txt").mode() == 33188
     left:  33206
     right: 33188
     stacktrace:
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:89: (test)

.

  2) test create with files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:43
     Assertion with != failed, both sides are exactly equal
     code: assert File.stat!("unzip/empty_dir").mtime() != mtime_empty_dir
     left: {{2018, 4, 9}, {0, 55, 13}}
     stacktrace:
       test/mix/tasks/hex.build_test.exs:71: anonymous fn/0 in Mix.Tasks.Hex.BuildTest."test create with files"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:46: (test)

....................................................

Finished in 11.5 seconds
173 tests, 2 failures, 7 skipped

Randomized with seed 918000
```
Definitely going to get decreased returns from trying to get these two tests working in Windows, and I'm tempted to suggest just skipping them.  Trying to get mtime/ctime checks consistent across platforms tends to be difficult.

Not too sure about the mode test.  0100666 != 0100644.  Windows ACLs don't map well to unix-style file permissions... I'd suggest testing if the actual file permissions contain at least the mask 0644, but the last octet may be 0 in a system with the guest account disabled, or in some directory structures.  For that matter, the second octet may be 0 in some directory structures.

**Comment by ericmj** [comment]
Closing due to lack of activity. If someone wants to fix the last Windows tests that would be appreciated.
