### ISSUE TITLE
Hex times out every time (Singapore)

### ISSUE THREAD

**Issue by jfrolich** [hexpm/hex#537]
Hex 'reliably' times out on a 60 seconds timeout. I have quite a few dependencies, and a large number of git based dependencies, which could be the cause of the timeout?

I have to connect to a VPN in the US to make it work.

This has been happening for me for over 2 weeks.

```
~/D/d/c/backend (master|✔) > mix deps.get
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "httpotion"}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:830: GenServer.call/3
    (hex) lib/hex/registry/server.ex:54: Hex.Registry.Server.versions/2
    (hex) lib/hex/remote_converger.ex:316: Hex.RemoteConverger.verify_dep/3
    (elixir) lib/enum.ex:748: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1920: Enum.each/2
    (hex) lib/hex/remote_converger.ex:40: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
```

The package it times out on (`{:versions, "hexpm", "httpotion"}`) is different every time.

**Comment by kanishkablack** [comment]
It might be an error of fastly

**Comment by jfrolich** [comment]
Looks to be resolved after installing reinstalling hex
