### ISSUE TITLE
Regression: 0.17.6 fails with elixir-1.4.5 and otp 19.3

### ISSUE THREAD

**Issue by mdillavou** [hexpm/hex#550]
I have several projects that are no longer able to successfully run `mix.deps`. These projects worked fine with hex-0.17.3, but now fail with hex-0.17.6. This is when running Elixir-1.4.5 and OTP-19.3.

```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  base64url 0.0.1
  bbmustache 1.0.4
  bunt 0.2.0
  certifi 1.0.0
  cf 0.2.2
  comeonin 3.0.2
  conform_exrm 1.0.0
  cowboy 1.1.2
  cowlib 1.0.2
  credo 0.7.1
  dialyxir 0.5.1
  dogma 0.1.14
  elixir_make 0.4.0
  erlsom 1.4.1
  erlware_commons 0.22.0
  ex_aws 1.1.2
  ex_json_schema 0.5.5
  exrm 1.0.8
  getopt 0.8.2
  gproc 0.6.1
  guardian 0.14.2
  hackney 1.7.1
  hexate 0.6.1
  httpoison 0.11.1
  idna 4.0.0
  jose 1.8.2
  logger_file_backend 0.0.9
  maru 0.12.5
  meck 0.8.4
  metrics 1.0.1
  mime 1.1.0
  mimerl 1.0.2
  mock 0.2.1
  neotoma 1.7.3
  pipe 0.0.2
  plug 1.4.3
  poison 3.1.0
  providers 1.6.0
  ranch 1.3.2
  relx 3.22.0
  secure_random 0.5.1
  ssl_verify_fun 1.1.1
  sweet_xml 0.6.5
  temp 0.4.1
  uuid 1.1.7
* Updating pipe (Hex package)
** (ArgumentError) argument error
    :erlang.binary_to_atom('mix', :utf8)
    (elixir) lib/string.ex:1824: String.to_atom/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (hex) lib/hex/scm.ex:147: Hex.SCM.update/1
    (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:177: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:186: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:116: Mix.Dep.Converger.all/7
```

**Comment by mdillavou** [comment]
I believe the issue is with the `Hex.unpack_tar!` modifications.

**Comment by wojtekmach** [comment]
The fix is on master and there will likely be a new release today, sorry for inconvenience.

**Comment by mdillavou** [comment]
Thanks for the quick fix. Everything is working correctly with 0.17.7.
