### ISSUE TITLE
deps.get does not work in parallel 

### ISSUE THREAD

**Issue by fazibear** [hexpm/hex#570]
When you try to lunch `mix deps.get` simultaneously for the same project located in different directories, you'll get:

```
** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:badmatch, {:error, {:not_a_log_file, '/var/jenkins_home/.hex/cache.ets'}}}
    (hex) lib/hex/registry/server.ex:274: Hex.Registry.Server.persist/2
    (hex) lib/hex/registry/server.ex:143: anonymous fn/3 in Hex.Registry.Server.handle_call/3
    (hex) lib/hex/registry/server.ex:437: Hex.Registry.Server.wait_closing/2
    (hex) lib/hex/registry/server.ex:141: Hex.Registry.Server.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

12:29:56.220 [error] GenServer Hex.Registry.Server terminating
** (MatchError) no match of right hand side value: {:error, {:not_a_log_file, '/var/jenkins_home/.hex/cache.ets'}}
    (hex) lib/hex/registry/server.ex:274: Hex.Registry.Server.persist/2
    (hex) lib/hex/registry/server.ex:143: anonymous fn/3 in Hex.Registry.Server.handle_call/3
    (hex) lib/hex/registry/server.ex:437: Hex.Registry.Server.wait_closing/2
    (hex) lib/hex/registry/server.ex:141: Hex.Registry.Server.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.74.0>): :close
```

Temporary fix for that is to set `HEX_HOME` variable to separate dirs.

**Comment by ericmj** [comment]
I'm not sure if we can or how to fix this. I guess the cache file we are using is corrupted when we write to it from two processes.

**Comment by fazibear** [comment]
Maybe some kind of locking mechanism could fix the problem. Mix shouldn't throw the exception like this.

**Comment by ericmj** [comment]
I agree we shouldn’t throw if we can avoid it. Contributions are welcome if you know how to fix it.

**Comment by ericmj** [comment]
Closing since we don't have a solution for this.
