### ISSUE TITLE
mix deps.get failing on CI: "Task #PID<x.x.x> started from :hex_fetcher terminating"

### ISSUE THREAD

**Issue by fertapric** [hexpm/hex#586]
```
$ mix hex.info
Hex:    0.18.0
Elixir: 1.6.6
OTP:    21.0.1

Built with: Elixir 1.6.6 and OTP 19.3

$ elixir -v
Erlang/OTP 21 [erts-10.0.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 21)
```

The code works locally, but it fails consistently in Travis CI:

```
$ mix deps.get

20:39:52.766 [error] Task #PID<0.143.0> started from :hex_fetcher terminating
** (FunctionClauseError) no function clause matching in String.to_charlist/1
    (elixir) lib/string.ex:2037: String.to_charlist(nil)
    (hex) lib/hex/http/ssl.ex:56: Hex.HTTP.SSL.ssl_opts/1
    (hex) lib/hex/http.ex:34: Hex.HTTP.build_http_opts/2
    (hex) lib/hex/http.ex:9: Hex.HTTP.request/5
    (hex) lib/hex/registry/server.ex:320: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<16.115348921/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "bunt"}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (hex) lib/hex/registry/server.ex:56: Hex.Registry.Server.versions/2
    (hex) lib/hex/remote_converger.ex:419: Hex.RemoteConverger.verify_dep/3
    (elixir) lib/enum.ex:743: anonymous fn/3 in Enum.each/2
    (stdlib) maps.erl:257: :maps.fold_1/3
    (elixir) lib/enum.ex:1915: Enum.each/2
    (hex) lib/hex/remote_converger.ex:40: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
```

**mix.exs**
```elixir
  defp deps do
    [
      {:country, "~> 1.0", organization: "accountyn", optional: true},
      {:ecto, "~> 2.2", optional: true},

      # Development dependencies
      {:credo, "~> 0.9.3", only: :dev, runtime: false},
      {:dialyxir, "~> 0.5.1", only: :dev, runtime: false},

      # Docs dependencies
      {:ex_doc, "~> 0.18.3", only: :docs}
    ]
  end
```

**mix.lock**
```elixir
%{
  "bunt": {:hex, :bunt, "0.2.0", "951c6e801e8b1d2cbe58ebbd3e616a869061ddadcc4863d0a2182541acae9a38", [:mix], [], "hexpm"},
  "country": {:hex, :country, "1.0.0", "4507fe374e77259ba146908710430a79f74191a4cb31cf119a5cb6ac4d071d5d", [:mix], [{:ecto, "~> 2.2", [hex: :ecto, repo: "hexpm", optional: true]}, {:language_locale, "~> 1.0", [hex: :language_locale, repo: "hexpm:accountyn", optional: true]}], "hexpm:accountyn"},
  "credo": {:hex, :credo, "0.9.3", "76fa3e9e497ab282e0cf64b98a624aa11da702854c52c82db1bf24e54ab7c97a", [:mix], [{:bunt, "~> 0.2.0", [hex: :bunt, repo: "hexpm", optional: false]}, {:poison, ">= 0.0.0", [hex: :poison, repo: "hexpm", optional: false]}], "hexpm"},
  "decimal": {:hex, :decimal, "1.5.0", "b0433a36d0e2430e3d50291b1c65f53c37d56f83665b43d79963684865beab68", [:mix], [], "hexpm"},
  "dialyxir": {:hex, :dialyxir, "0.5.1", "b331b091720fd93e878137add264bac4f644e1ddae07a70bf7062c7862c4b952", [:mix], [], "hexpm"},
  "earmark": {:hex, :earmark, "1.2.5", "4d21980d5d2862a2e13ec3c49ad9ad783ffc7ca5769cf6ff891a4553fbaae761", [:mix], [], "hexpm"},
  "ecto": {:hex, :ecto, "2.2.10", "e7366dc82f48f8dd78fcbf3ab50985ceeb11cb3dc93435147c6e13f2cda0992e", [:mix], [{:db_connection, "~> 1.1", [hex: :db_connection, repo: "hexpm", optional: true]}, {:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.8.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, repo: "hexpm", optional: true]}], "hexpm"},
  "ex_doc": {:hex, :ex_doc, "0.18.3", "f4b0e4a2ec6f333dccf761838a4b253d75e11f714b85ae271c9ae361367897b7", [:mix], [{:earmark, "~> 1.1", [hex: :earmark, repo: "hexpm", optional: false]}], "hexpm"},
  "poison": {:hex, :poison, "3.1.0", "d9eb636610e096f86f25d9a46f35a9facac35609a7591b3be3326e99a0484665", [:mix], [], "hexpm"},
  "poolboy": {:hex, :poolboy, "1.5.1", "6b46163901cfd0a1b43d692657ed9d7e599853b3b21b95ae5ae0a777cf9b6ca8", [:rebar], [], "hexpm"},
}
```

Btw, I tried removing the organization dependency (just to discard things), and `mix deps.get` still fails 😞 

If it helps, I can create a new Travis build and give SSH access to it :)

**Comment by fertapric** [comment]
Forget what I said, it was to be related to organizations.

Here is the problem:

On the CI:

```
circleci@a033ae5a44e0:~/project$ cat ~/.hex/hex.config
{'$repos',#{<<"hexpm:accountyn">> =>
                #{auth_key => <<"xxx">>,
                  url => <<"/repos/accountyn">>}}}.
```

On my local machine:

```
23:28:57 . master timezone $ cat ~/.hex/hex.config
{username,<<"fertapric">>}.
{'$encrypted_key',<<"xxx">>}.
{'$repos',#{<<"hexpm:accountyn">> =>
                #{auth_key => <<"xxx">>,
                  public_key => nil,
                  url => <<"https://repo.hex.pm/repos/accountyn">>}}}.
```

The URL param in `~/.hex/config` in the CI `/repos/accountyn` was passed around until it hit [`URI.parse(url).host`](https://github.com/hexpm/hex/blob/master/lib/hex/http/ssl.ex#L56) being the `url` `/repos/accountyn/my_package`.

The only thing I miss is how that got misconfigured 🤔

**Comment by mpiercy827** [comment]
We are seeing the same issue on CircleCI, but things seem to be working normally.

**Comment by fertapric** [comment]
I think this the [offending change](https://github.com/hexpm/hex/pull/559/files#diff-4d6d7c90162640528afa283810570fefL151).

**Comment by dmlittle** [comment]
@fertapric I spoke with Eric earlier today and confirmed there's a bug with organization authentication. He said there'd be a fix tomorrow for it.

**Comment by LanfordCai** [comment]
@dmlittle We are using hex in production, this bug would be a block for our work. I want to know whether rollback hex version would solve this problem? If so, how to do the rollback? I didn't find the method in the hex doc.

**Comment by hupengbuaa** [comment]
Is it possible to `mix local.hex` with a specific version? I am trying to install the old version, suppose it would work.

**Comment by dmlittle** [comment]
@LanfordCai as far as I understand it, this is an issue with the Hex servers not accepting valid credentials so updating your local version of hex won't solve the issue. I'm not affiliated with Hex so I have no way to solve the underlying problem. I'm just listed as a contributor because I've put up a PR in the past.

**Comment by LanfordCai** [comment]
@dmlittle I want to appoint a specific hex version in my dockerfile. @hupengbuaa have came up with an idea to solve this problem: clone hex code, checkout to specific version and install it in dockerfile.

**Comment by ericmj** [comment]
I have identified the issue and will release a hotfix.

You can install a specific version by running `mix hex.install 0.17.8` this only works after you have run `mix local.hex`. In the future `mix local.hex` will also accept a specific version to install.

**Comment by ericmj** [comment]
I have released a hotfix that should fix the issue. Sorry for the inconvenience.
