### ISSUE TITLE
can not fetch dependencies from organization repo

### ISSUE THREAD

**Issue by tim2CF** [hexpm/hex#605]
In CI I'm trying to build project with private hex dependencies

```
mix hex.organization auth $ORGANIZATION --key $HEX_API_KEY
```

Auth command returns code 0, ok. But when script tries to fetch dependencies

```
09:12:35.072 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (KeyError) key :public_key not found in: %{auth_key: "**********************"}
            (hex) lib/hex/config.ex:137: anonymous fn/2 in Hex.Config.update_organizations/1
            (elixir) lib/map.ex:210: Map.new_transform/3
            (hex) lib/hex/state.ex:58: Hex.State.init/1
            (elixir) lib/agent/server.ex:8: Agent.Server.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by ericmj** [comment]
What hex version are you using on CI? The latest version is 0.18.1, but it seems like you are not using it.

You can check with `mix hex.info`.

**Comment by tim2CF** [comment]
issue fixed, thanks!
