### ISSUE TITLE
Publish error when package has a dependency with git options 

### ISSUE THREAD

**Issue by dideler** [hexpm/hex#635]
Getting an `ArgumentError` when trying to publish a package that has a dependency on a git repository (workaround until that dependency publishes a new version to hex.pm).

```elixir
  defp deps do
    [
      {:ex_doc, "~> 0.19", only: :dev, runtime: false},
      {:ex_aws, git: "https://github.com/ex-aws/ex_aws.git", ref: "master"}
    ]
  end
```

```
$ mix hex.publish
** (ArgumentError) you attempted to apply :app on {:ex_aws, nil, [git: "https://github.com/ex-aws/ex_aws.git", ref: "master"]}. If you are using apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function, make sure the left side of the dot is an atom or a map
    :erlang.apply({:ex_aws, nil, [git: "https://github.com/ex-aws/ex_aws.git", ref: "master"]}, :app, [])
    (hex) lib/mix/tasks/hex.build.ex:251: anonymous fn/1 in Mix.Tasks.Hex.Build.dependencies/0
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (hex) lib/mix/tasks/hex.build.ex:251: Mix.Tasks.Hex.Build.dependencies/0
    (hex) lib/mix/tasks/hex.build.ex:130: Mix.Tasks.Hex.Build.prepare_package/0
    (hex) lib/mix/tasks/hex.publish.ex:108: Mix.Tasks.Hex.Publish.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

```
$ mix hex.info
Hex:    0.18.2
Elixir: 1.7.3
OTP:    21.0.9

Built with: Elixir 1.7.4 and OTP 19.3
```

**Comment by ericmj** [comment]
A better error message should be shown but note that Hex does not support git dependencies.

**Comment by dideler** [comment]
Okay, I'll submit a patch for a better error message.
