### ISSUE TITLE
New Install, getting timeout error with 'mix local.hex'

### ISSUE THREAD

**Issue by sm-tradeboox** [hexpm/hex#691]
Hello. 

I have a new install of elixir on Ubuntu 16.04. I keep getting a timeout error.

```
gqlmgr@gqld1a:~/projects/graphql$ HEX_HTTP_CONCURRENCY=4 MIX_DEBUG=1 mix local.hex
** Running mix loadconfig
** Running mix local.hex
** (Mix.Error) request timed out after 60000ms

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.

    (mix) lib/mix.ex:375: Mix.raise/1
    (mix) lib/mix/local.ex:126: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.hex.ex:57: Mix.Tasks.Local.Hex.run_install/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

There's no issues with DNS or connecting with the repo, as download of the file indicated isn't an issue.

```
gqlmgr@gqld1a:~/projects/graphql$ wget https://repo.hex.pm/installs/hex-1.x.csv
--2019-04-11 01:24:03--  https://repo.hex.pm/installs/hex-1.x.csv
Resolving repo.hex.pm (repo.hex.pm)... 2a04:4e42:e::514, 151.101.58.2
Connecting to repo.hex.pm (repo.hex.pm)|2a04:4e42:e::514|:443... failed: Network is unreachable.
Connecting to repo.hex.pm (repo.hex.pm)|151.101.58.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17182 (17K) [text/csv]
Saving to: ‘hex-1.x.csv.2’

hex-1.x.csv.2                    100%[=======================================================>]  16.78K  --.-KB/s    in 0.005s  

2019-04-11 01:24:04 (3.29 MB/s) - ‘hex-1.x.csv.2’ saved [17182/17182]
```

```
gqlmgr@gqld1a:~/projects/graphql$ elixir -v
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

Thanks for your help.

Sam

**Comment by sm-tradeboox** [comment]
Hello.

This may be related.

I tried compiling elixir from source and some of the tests are failing. All failures seem to be due to lack of response from the epmd service. 

Failed tests listed below -

```
gqlmgr@gqld1a:~/elixir-src/elixir$ make test
bin/elixir bin/mix format --check-formatted
==> elixir (eunit)
  All 207 tests passed.

==> elixir (ex_unit)
Excluding tags: [windows: true]

  1) test invokes command on remote node (Kernel.CLI.RPCTest)
     test/elixir/kernel/cli_test.exs:73
     Assertion with == failed
     code:  assert rpc_eval("IO.puts :ok") == "ok\n"
     left:  "Protocol 'inet_tcp': register/listen error: no_reg_reply_from_epmd\r\n"
     right: "ok\n"
     stacktrace:
       test/elixir/kernel/cli_test.exs:74: (test)



  2) test properly formats errors (Kernel.CLI.RPCTest)
     test/elixir/kernel/cli_test.exs:77
     Expected truthy, got false
     code: assert String.starts_with?(rpc_eval(":erlang.error 1"), "** (ErlangError) Erlang error: 1")
     arguments:

         # 1
         "Protocol 'inet_tcp': register/listen error: no_reg_reply_from_epmd\r\n"

         # 2
         "** (ErlangError) Erlang error: 1"

     stacktrace:
       test/elixir/kernel/cli_test.exs:79: (test)

01:42:08.756 [info]  Protocol 'inet_tcp': register/listen error: no_reg_reply_from_epmd



  3) test start/3 and stop/0 (NodeTest)
     test/elixir/node_test.exs:9
     match (=) failed
     code:  assert {:ok, _} = Node.start(:hello, :shortnames, 15000)
     right: {:error,
             {{:shutdown,
               {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},
              {:child, :undefined, :net_sup_dynamic,
               {:erl_distribution, :start_link,
                [[:hello, :shortnames, 15000], false]}, :permanent, 1000,
               :supervisor, [:erl_distribution]}}}
     stacktrace:
       test/elixir/node_test.exs:11: (test)

Finished in 49.2 seconds (12.4s on load, 36.8s on tests)
1483 doctests, 3143 tests, 3 failures, 7 excluded

Randomized with seed 509063
Makefile:267: recipe for target 'test_stdlib' failed
make: *** [test_stdlib] Error 1

```

Trying to figure out what's causing this error.

Thanks.

Sam

**Comment by sm-tradeboox** [comment]
Forgot to add the response from epmd running in debug mode.

```
# epmd -d
epmd: Thu Apr 11 03:20:27 2019: epmd running - daemon = 0
epmd: Thu Apr 11 03:22:09 2019: ** got ALIVE2_REQ
epmd: Thu Apr 11 03:22:09 2019: registering 'cli-rpc-576460752303417463:1', port 43308
epmd: Thu Apr 11 03:22:09 2019: type 77 proto 0 highvsn 5 lowvsn 5
epmd: Thu Apr 11 03:22:09 2019: ** sent ALIVE2_RESP for "cli-rpc-576460752303417463"
epmd: Thu Apr 11 03:22:19 2019: unregistering 'cli-rpc-576460752303417463:1', port 43308
epmd: Thu Apr 11 03:22:19 2019: ** got ALIVE2_REQ
epmd: Thu Apr 11 03:22:19 2019: registering 'cli-rpc-576460752303415357:2', port 51326
epmd: Thu Apr 11 03:22:19 2019: type 77 proto 0 highvsn 5 lowvsn 5
epmd: Thu Apr 11 03:22:19 2019: ** sent ALIVE2_RESP for "cli-rpc-576460752303415357"
epmd: Thu Apr 11 03:22:29 2019: unregistering 'cli-rpc-576460752303415357:2', port 51326
epmd: Thu Apr 11 03:22:33 2019: ** got ALIVE2_REQ
epmd: Thu Apr 11 03:22:33 2019: registering 'hello:1', port 57018
epmd: Thu Apr 11 03:22:33 2019: type 77 proto 0 highvsn 5 lowvsn 5
epmd: Thu Apr 11 03:22:33 2019: ** sent ALIVE2_RESP for "hello"
epmd: Thu Apr 11 03:22:43 2019: unregistering 'hello:1', port 57018
```

SO epmd is getting messages, just not sending responses? Or responses are not getting back to source?

**Comment by ericmj** [comment]
It looks like wget failed when trying the ipv6 address, unfortunately the HTTP client we use don't have fallback to ipv4 afaik. Try disabling ipv6 on your OS.

**Comment by sm-tradeboox** [comment]
I don't believe I have IPv6 running. PROCFS doesn't show any entries for IPv6. Anyway, for wget, fallback is IPv4 and there's no problem there. 

Thanks.

**Comment by ericmj** [comment]
You definitely at least have DNS resolution set up to resolve IPv6 addresses, and you are unable to connect with the IPv6 address. Compare your output to mine:

```
wget https://repo.hex.pm/installs/hex-1.x.csv
--2019-04-11 13:21:50--  https://repo.hex.pm/installs/hex-1.x.csv
Resolving repo.hex.pm (repo.hex.pm)... 151.101.114.2
Connecting to repo.hex.pm (repo.hex.pm)|151.101.114.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17182 (17K) [text/csv]
Saving to: ‘hex-1.x.csv’
```

As I said, the HTTP client we use doesn't do the fallback wget does. So if IPv6 is resolved but doesn't work then you won't be able to fetch hex.

**Comment by ericmj** [comment]
Since you can fetch with wget another way of installing Hex is:

```
wget https://repo.hex.pm/installs/1.8.0/hex-0.19.0.ez
mix archive.install hex-0.19.0.ez
```

**Comment by ericmj** [comment]
@sm-tradeboox Unfortunately I can't test IPv6 so can you please do a test for me? Try the following in `iex` and paste the output:

```iex
iex(1)> :gen_tcp.connect('repo.hex.pm', 443, [], 5000)
{:ok, #Port<0.6>}
iex(2)> :gen_tcp.connect('151.101.114.2', 443, [], 5000)
{:ok, #Port<0.7>}
iex(3)> :gen_tcp.connect('2a04:4e42:e::514', 443, [], 5000)
{:error, :nxdomain}
```

If you wan't to look at related issues please check here: https://github.com/elixir-lang/elixir/search?q=ipv6&type=Issues

**Comment by sm-tradeboox** [comment]
Hello @ericmj .

Please see below, matches your output.

```
gqlmgr@gqld1a:~$ iex
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :gen_tcp.connect('repo.hex.pm', 443, [], 5000)
{:ok, #Port<0.6>}
iex(2)> :gen_tcp.connect('151.101.114.2', 443, [], 5000)
{:ok, #Port<0.7>}
iex(3)> :gen_tcp.connect('2a04:4e42:e::514', 443, [], 5000)
{:error, :nxdomain}
iex(4)> 
```

**Comment by ericmj** [comment]
Thank you, can you please also check what `:inet_res.gethostbyname('repo.hex.pm')` returns?

**Comment by sm-tradeboox** [comment]
```
iex(1)> :inet_res.gethostbyname('repo.hex.pm')
{:ok,
 {:hostent, 'dualstack.f2.shared.global.fastly.net', ['repo.hex.pm'], :inet, 4,
  [{199, 232, 34, 2}]}}
```

**Comment by ericmj** [comment]
It looks like my assumption that it is an IPv6 is wrong. Then I don't know what the issue is unfortunately.

**Comment by supersimple** [comment]
@sm-tradeboox  is this still an issue for you?

**Comment by sm-tradeboox** [comment]
Hi. Not sure if this is still an issue, we moved dev to another machine where it wasn't an error. Thanks.

**Comment by sm-tradeboox** [comment]
OK now I remember!

Not directly related, but it's related to another item I posted above. And I felt the 2 may be related. But the error seems to be related to the underlying OS.

We do most of our development on SmartOS VMs. We use both native Illumnos and LXC (linux) containers. Usually it's Ubuntu-based containers on LXC. 

It seems that the Erlang epmd service requires direct access to a virtual device that's not available in the LXC VM. So things seem to work fine on native containers and bare metal installs, but not in the VM. 

`Unable to access devicec 203:0`

Hope this helps someone.

**Comment by supersimple** [comment]
@sm-tradeboox ooh, that _is_ interesting.
@josevalim @ericmj is this something for the OTP group to be made aware of?
