### ISSUE TITLE
mix deps.get is failing due to `GenServer Hex.Registry.Server terminating`

### ISSUE THREAD

**Issue by Skoda091** [hexpm/hex#702]
## Problem
When I try `mix deps.get`, I'll get:

### Output:
```
14:02:59.116 [error] GenServer Hex.Registry.Server terminating
** (ArgumentError) argument error
    (stdlib) :ets.insert(#Reference<0.573667077.1102970888.198328>, [{{:retired, "hexpm", "distillery", "1.5.1"}, nil}, {{:retired, "hexpm", "appsignal", "1.4.8"}, nil}, {{:retired, "hexpm", "basic_auth", "0.0.2"}, nil}, {{:deps, "hexpm", "plug", "1.5.1"}, [{"hexpm", "cowboy", "cowboy", "~> 1.0.1 or ~> 1.1 or ~> 2.3", true}, {"hexpm", "mime", "mime", "~> 1.0", false}]}, {{:checksum, "hexpm", "lager", "3.6.8"}, <<137, 126, 252, 118, 121, 187, 130, 56, 52, 72, 100, 108, 150, 118, 140, 220, 78, 116, 116, 100, 221, 24, 185, 153, 199, 170, 202, 72, 86, 134, 176, 218>>}, {{:retired, "hexpm", "ecto", "2.1.0-rc.0"}, nil}, {{:retired, "hexpm", "db_connection", "1.0.0-rc.4"}, nil}, {{:deps, "hexpm", "hackney", "1.4.6"}, [{"hexpm", "certifi", "certifi", "0.3.0", false}, {"hexpm", "idna", "idna", "1.0.2", false}, {"hexpm", "mimerl", "mimerl", "1.0.0", false}, {"hexpm", "ssl_verify_hostname", "ssl_verify_hostname", "1.0.5", false}]}, {{:deps, "hexpm", "credo", "0.8.2"}, [{"hexpm", "bunt", "bunt", "~> 0.2.0", false}]}, {{:retired, "hexpm", "telemetry", "0.1.0"}, nil}, {{:checksum, "hexpm", "ecto", "2.2.0-rc.1"}, <<153, 11, 152, 219, 142, 0, 34, 171, 90, 195, 0, 198, 225, 242, 100, 237, 198, 234, 6, 6, 87, 201, 186, 121, 121, 245, 202, 104, 206, 107, 130, 35>>}, {{:retired, "hexpm", "phoenix_ecto", "3.1.0"}, nil}, {{:retired, "hexpm", "httpoison", "0.10.0"}, nil}, {{:retired, "hexpm", "lager", "3.5.2"}, nil}, {{:checksum, "hexpm", "gettext", "0.13.0"}, <<218, 175, 189, 220, 92, 218, 18, 115, 139, 185, 59, 1, 216, 65, 5, 254, 117, 185, 22, 163, 2, 241, 197, 10, 185, 251, 6, 107, 149, 236, 157, 180>>}, {{:checksum, "hexpm", "horde", "0.5.0-rc.3"}, <<185, 140, 97, 25, 86, 1, 95, 234, 194, 109, 151, 54, 116, 22, 81, 172, 184, 21, 48, 99, 250, 15, 26, 91, 194, 186, 193, 170, 65, 125, 74, 129>>}, {{:checksum, "hexpm", "poolboy", "1.2.1"}, <<190, 23, 125, 88, 205, 137, 48, 53, 168, 38, 140, 179, 108, 216, 165, 7, 224, 163, 229, 173, 136, 217, 16, 223, 21, 235, 30, 31, 188, 201, 192, ...>>}, {{:deps, "hexpm", "phoenix_html", "2.9.1"}, [{"hexpm", "plug", "plug", "~> 1.0", false}]}, {{:checksum, "hexpm", "gen_stage", "0.5.0"}, <<117, 128, 104, 243, 168, 18, 134, 227, 66, 166, 9, 214, 104, 233, 98, 71, 20, 194, 228, 212, 60, 194, 102, 153, 234, 208, 77, 22, 128, ...>>}, {{:checksum, "hexpm", "comeonin", "2.6.0"}, <<116, 194, 136, 51, 139, 51, 32, 95, 156, 233, 126, 33, 23, 187, 154, 42, 170, 177, 3, 161, 129, 29, 36, 52, 67, 215, 111, 219, ...>>}, {{:retired, "hexpm", "uuid", "1.1.0"}, nil}, {{:checksum, "hexpm", "plug", "0.8.4"}, <<68, 63, 248, 179, 43, 127, 244, 32, 19, 143, 198, 19, 95, 15, 103, 186, 0, 120, 176, 137, 102, 154, 98, 188, 21, 83, ...>>}, {{:checksum, "hexpm", "phoenix_html", "2.10.3"}, <<67, 45, 236, 158, 4, 55, 46, 235, 122, 109, 191, 89, 167, 120, 207, 67, 235, 68, 81, 132, 65, 147, 34, 23, 55, ...>>}, {{:versions, "hexpm", "delta_crdt"}, ["0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4", "0.1.5", "0.1.6", "0.1.7", "0.1.8", "0.1.9", "0.1.10", "0.1.11", "0.2.0", "0.2.1", "0.3.0-rc1", "0.3.0-rc2", "0.3.0", "0.3.1", "0.4.0", "0.4.1", "0.4.2", "0.4.3", "0.5.0", "0.5.1", ...]}, {{:checksum, "hexpm", "ex_aws", "0.4.10"}, <<241, 14, 150, 222, 0, 28, 213, 247, 218, 33, 78, 107, 250, 196, 174, 143, 117, 5, 29, 35, 11, 135, 26, ...>>}, {{:retired, "hexpm", "credo", "0.7.2"}, nil}, {{:deps, "hexpm", "jsx", "2.2.0"}, []}, {{:deps, "hexpm", "parallel_stream", "1.0.5"}, []}, {{:deps, "hexpm", "ecto", "3.0.8"}, [{"hexpm", "decimal", "decimal", "~> 1.6", false}, {"hexpm", "jason", "jason", "~> 1.0", true}, {"hexpm", "poison", "poison", "~> 2.2 or ~> 3.0", true}]}, {{:checksum, "hexpm", "verk", "1.6.0"}, <<153, 17, 207, 166, 177, 35, 251, 202, 68, 1, 234, 20, 53, 245, 200, 127, 32, 110, ...>>}, {{:checksum, "hexpm", "esaml", "3.1.0"}, <<118, 51, 127, 0, 181, 149, 58, 108, 36, 159, 168, 195, 34, 144, 92, 122, 6, ...>>}, {{:deps, "hexpm", "phoenix_ecto", "3.2.1"}, [{"hexpm", "ecto", "ecto", "~> 2.1", false}, {"hexpm", "phoenix_html", "phoenix_html", "~> 2.9", false}, {"hexpm", "plug", "plug", "~> 1.0", false}]}, {{:deps, "hexpm", "comeonin", "5.0.0"}, []}, {{:retired, "hexpm", "timex", "3.0.3"}, nil}, {{:retired, "hexpm", "comeonin", "4.1.2"}, nil}, {{:checksum, "hexpm", "tzdata", "0.1.201805"}, <<254, 183, 107, 72, 177, 98, 30, 127, 102, 160, 36, 121, ...>>}, {{:checksum, "hexpm", "amqp_client", "3.7.11-rc.2"}, <<236, 147, 53, 187, 33, 161, 202, 21, 29, 232, 223, ...>>}, {{:checksum, "hexpm", "telemetry", "0.3.0"}, <<9, 154, 127, 60, 227, 30, 71, 128, 249, 113, ...>>}, {{:versions, "hexpm", "ecto"}, ["0.1.0", "0.2.0", "0.2.1", "0.2.2", "0.2.3", "0.2.4", "0.2.5", "0.2.6", "0.2.7", ...]}, {{:deps, "hexpm", "appsignal", "1.3.6"}, [{"hexpm", "decorator", "decorator", "~> 1.2.2", false}, {"hexpm", "httpoison", "httpoison", "~> 0.11", false}, {"hexpm", "phoenix", "phoenix", ">= 1.2.0", true}, {"hexpm", "plug", "plug", ">= 1.1.0", ...}, {"hexpm", "poison", "poison", ...}]}, {{:checksum, "hexpm", "csv", "2.0.0"}, <<198, 111, 234, 137, 186, 120, 98, ...>>}, {{:deps, "hexpm", "jason", "1.0.0"}, [{"hexpm", "decimal", "decimal", "~> 1.0", true}]}, {{:checksum, "hexpm", "appsignal", "1.5.0"}, <<192, 246, 240, 238, 178, ...>>}, {{:deps, "hexpm", "xml_builder", "0.0.9"}, []}, {{:deps, "hexpm", "credo", "0.10.2"}, [{"hexpm", "bunt", ...}, {"hexpm", ...}]}, {{:registry_etag, "hexpm", "secure_random"}, "\"4191518782dd2d261ea31abce7651a21\""}, {{:deps, "hexpm", ...}, [{...}, ...]}, {{:deps, ...}, [...]}, {{...}, ...}, {...}, ...])
    (stdlib) ets.erl:1357: :ets.load_table/3
    (stdlib) ets.erl:1105: :ets.do_read_and_verify/6
    (stdlib) ets.erl:1081: :ets.file2tab/2
    (hex) lib/hex/registry/server.ex:240: Hex.Registry.Server.open_ets/1
    (hex) lib/hex/registry/server.ex:121: Hex.Registry.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
Last message (from #PID<0.91.0>): {:open, []}
State: %{closing_fun: nil, ets: nil, fetched: #MapSet<[]>, path: nil, pending: #MapSe** (UndefinedFunctionError) function :badarg.exception/1 is undefined (module :badarg is not available)
    :badarg.exception([])
    (hex) lib/hex/registry/server.ex:33: Hex.Registry.Server.open/1
    (hex) lib/hex/remote_converger.ex:18: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
t<[]>, waiting: %{}}
Client #PID<0.91.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (hex) lib/hex/registry/server.ex:32: Hex.Registry.Server.open/1
    (hex) lib/hex/remote_converger.ex:18: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1

14:02:59.121 [error] GenServer Hex.UpdateChecker terminating
** (UndefinedFunctionError) function :badarg.exception/1 is undefined (module :badarg is not available)
    :badarg.exception([])
    (hex) lib/hex/registry/server.ex:89: Hex.Registry.Server.last_update/0
    (hex) lib/hex/update_checker.ex:110: Hex.UpdateChecker.check_update?/0
    (hex) lib/hex/update_checker.ex:29: Hex.UpdateChecker.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :start_check}
State: %{done: false, from: nil, reply: nil, started: false}
```
## Debug info
* `mix hex.config`:
```
api_url: "https://hex.pm/api" (default)
api_key: nil (default)
offline: false (default)
unsafe_https: false (default)
unsafe_registry: false (default)
no_verify_repo_origin: false (default)
http_proxy: nil (default)
https_proxy: nil (default)
http_concurrency: 8 (default)
http_timeout: nil (default)
home: "/Users/Adam/.hex" (default)
```
* `mix hex.info`:
```
Hex:    0.19.0
Elixir: 1.8.0
OTP:    21.2

Built with: Elixir 1.8.0 and OTP 20.2

14:08:27.620 [error] GenServer Hex.Registry.Server terminating
** (ArgumentError) argument error
    (stdlib) :ets.insert(#Reference<0.3646044139.3519414281.258000>, [{{:retired, "hexpm", "distillery", "1.5.1"}, nil}, {{:retired, "hexpm", "appsignal", "1.4.8"}, nil}, {{:retired, "hexpm", "basic_auth", "0.0.2"}, nil}, {{:deps, "hexpm", "plug", "1.5.1"}, [{"hexpm", "cowboy", "cowboy", "~> 1.0.1 or ~> 1.1 or ~> 2.3", true}, {"hexpm", "mime", "mime", "~> 1.0", false}]}, {{:checksum, "hexpm", "lager", "3.6.8"}, <<137, 126, 252, 118, 121, 187, 130, 56, 52, 72, 100, 108, 150, 118, 140, 220, 78, 116, 116, 100, 221, 24, 185, 153, 199, 170, 202, 72, 86, 134, 176, 218>>}, {{:retired, "hexpm", "ecto", "2.1.0-rc.0"}, nil}, {{:retired, "hexpm", "db_connection", "1.0.0-rc.4"}, nil}, {{:deps, "hexpm", "hackney", "1.4.6"}, [{"hexpm", "certifi", "certifi", "0.3.0", false}, {"hexpm", "idna", "idna", "1.0.2", false}, {"hexpm", "mimerl", "mimerl", "1.0.0", false}, {"hexpm", "ssl_verify_hostname", "ssl_verify_hostname", "1.0.5", false}]}, {{:deps, "hexpm", "credo", "0.8.2"}, [{"hexpm", "bunt", "bunt", "~> 0.2.0", false}]}, {{:retired, "hexpm", "telemetry", "0.1.0"}, nil}, {{:checksum, "hexpm", "ecto", "2.2.0-rc.1"}, <<153, 11, 152, 219, 142, 0, 34, 171, 90, 195, 0, 198, 225, 242, 100, 237, 198, 234, 6, 6, 87, 201, 186, 121, 121, 245, 202, 104, 206, 107, 130, 35>>}, {{:retired, "hexpm", "phoenix_ecto", "3.1.0"}, nil}, {{:retired, "hexpm", "httpoison", "0.10.0"}, nil}, {{:retired, "hexpm", "lager", "3.5.2"}, nil}, {{:checksum, "hexpm", "gettext", "0.13.0"}, <<218, 175, 189, 220, 92, 218, 18, 115, 139, 185, 59, 1, 216, 65, 5, 254, 117, 185, 22, 163, 2, 241, 197, 10, 185, 251, 6, 107, 149, 236, 157, 180>>}, {{:checksum, "hexpm", "horde", "0.5.0-rc.3"}, <<185, 140, 97, 25, 86, 1, 95, 234, 194, 109, 151, 54, 116, 22, 81, 172, 184, 21, 48, 99, 250, 15, 26, 91, 194, 186, 193, 170, 65, 125, 74, 129>>}, {{:checksum, "hexpm", "poolboy", "1.2.1"}, <<190, 23, 125, 88, 205, 137, 48, 53, 168, 38, 140, 179, 108, 216, 165, 7, 224, 163, 229, 173, 136, 217, 16, 223, 21, 235, 30, 31, 188, 201, 192, ...>>}, {{:deps, "hexpm", "phoenix_html", "2.9.1"}, [{"hexpm", "plug", "plug", "~> 1.0", false}]}, {{:checksum, "hexpm", "gen_stage", "0.5.0"}, <<117, 128, 104, 243, 168, 18, 134, 227, 66, 166, 9, 214, 104, 233, 98, 71, 20, 194, 228, 212, 60, 194, 102, 153, 234, 208, 77, 22, 128, ...>>}, {{:checksum, "hexpm", "comeonin", "2.6.0"}, <<116, 194, 136, 51, 139, 51, 32, 95, 156, 233, 126, 33, 23, 187, 154, 42, 170, 177, 3, 161, 129, 29, 36, 52, 67, 215, 111, 219, ...>>}, {{:retired, "hexpm", "uuid", "1.1.0"}, nil}, {{:checksum, "hexpm", "plug", "0.8.4"}, <<68, 63, 248, 179, 43, 127, 244, 32, 19, 143, 198, 19, 95, 15, 103, 186, 0, 120, 176, 137, 102, 154, 98, 188, 21, 83, ...>>}, {{:checksum, "hexpm", "phoenix_html", "2.10.3"}, <<67, 45, 236, 158, 4, 55, 46, 235, 122, 109, 191, 89, 167, 120, 207, 67, 235, 68, 81, 132, 65, 147, 34, 23, 55, ...>>}, {{:versions, "hexpm", "delta_crdt"}, ["0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4", "0.1.5", "0.1.6", "0.1.7", "0.1.8", "0.1.9", "0.1.10", "0.1.11", "0.2.0", "0.2.1", "0.3.0-rc1", "0.3.0-rc2", "0.3.0", "0.3.1", "0.4.0", "0.4.1", "0.4.2", "0.4.3", "0.5.0", "0.5.1", ...]}, {{:checksum, "hexpm", "ex_aws", "0.4.10"}, <<241, 14, 150, 222, 0, 28, 213, 247, 218, 33, 78, 107, 250, 196, 174, 143, 117, 5, 29, 35, 11, 135, 26, ...>>}, {{:retired, "hexpm", "credo", "0.7.2"}, nil}, {{:deps, "hexpm", "jsx", "2.2.0"}, []}, {{:deps, "hexpm", "parallel_stream", "1.0.5"}, []}, {{:deps, "hexpm", "ecto", "3.0.8"}, [{"hexpm", "decimal", "decimal", "~> 1.6", false}, {"hexpm", "jason", "jason", "~> 1.0", true}, {"hexpm", "poison", "poison", "~> 2.2 or ~> 3.0", true}]}, {{:checksum, "hexpm", "verk", "1.6.0"}, <<153, 17, 207, 166, 177, 35, 251, 202, 68, 1, 234, 20, 53, 245, 200, 127, 32, 110, ...>>}, {{:checksum, "hexpm", "esaml", "3.1.0"}, <<118, 51, 127, 0, 181, 149, 58, 108, 36, 159, 168, 195, 34, 144, 92, 122, 6, ...>>}, {{:deps, "hexpm", "phoenix_ecto", "3.2.1"}, [{"hexpm", "ecto", "ecto", "~> 2.1", false}, {"hexpm", "phoenix_html", "phoenix_html", "~> 2.9", false}, {"hexpm", "plug", "plug", "~> 1.0", false}]}, {{:deps, "hexpm", "comeonin", "5.0.0"}, []}, {{:retired, "hexpm", "timex", "3.0.3"}, nil}, {{:retired, "hexpm", "comeonin", "4.1.2"}, nil}, {{:checksum, "hexpm", "tzdata", "0.1.201805"}, <<254, 183, 107, 72, 177, 98, 30, 127, 102, 160, 36, 121, ...>>}, {{:checksum, "hexpm", "amqp_client", "3.7.11-rc.2"}, <<236, 147, 53, 187, 33, 161, 202, 21, 29, 232, 223, ...>>}, {{:checksum, "hexpm", "telemetry", "0.3.0"}, <<9, 154, 127, 60, 227, 30, 71, 128, 249, 113, ...>>}, {{:versions, "hexpm", "ecto"}, ["0.1.0", "0.2.0", "0.2.1", "0.2.2", "0.2.3", "0.2.4", "0.2.5", "0.2.6", "0.2.7", ...]}, {{:deps, "hexpm", "appsignal", "1.3.6"}, [{"hexpm", "decorator", "decorator", "~> 1.2.2", false}, {"hexpm", "httpoison", "httpoison", "~> 0.11", false}, {"hexpm", "phoenix", "phoenix", ">= 1.2.0", true}, {"hexpm", "plug", "plug", ">= 1.1.0", ...}, {"hexpm", "poison", "poison", ...}]}, {{:checksum, "hexpm", "csv", "2.0.0"}, <<198, 111, 234, 137, 186, 120, 98, ...>>},** (UndefinedFunctionError) function :badarg.exception/1 is undefined (module :badarg is not available)
    :badarg.exception([])
    (hex) lib/hex/registry/server.ex:33: Hex.Registry.Server.open/1
    (hex) lib/mix/tasks/hex.info.ex:57: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
 {{:deps, "hexpm", "jason", "1.0.0"}, [{"hexpm", "decimal", "decimal", "~> 1.0", true}]}, {{:checksum, "hexpm", "appsignal", "1.5.0"}, <<192, 246, 240, 238, 178, ...>>}, {{:deps, "hexpm", "xml_builder", "0.0.9"}, []}, {{:deps, "hexpm", "credo", "0.10.2"}, [{"hexpm", "bunt", ...}, {"hexpm", ...}]}, {{:registry_etag, "hexpm", "secure_random"}, "\"4191518782dd2d261ea31abce7651a21\""}, {{:deps, "hexpm", ...}, [{...}, ...]}, {{:deps, ...}, [...]}, {{...}, ...}, {...}, ...])
    (stdlib) ets.erl:1357: :ets.load_table/3
    (stdlib) ets.erl:1105: :ets.do_read_and_verify/6
    (stdlib) ets.erl:1081: :ets.file2tab/2
    (hex) lib/hex/registry/server.ex:240: Hex.Registry.Server.open_ets/1
    (hex) lib/hex/registry/server.ex:121: Hex.Registry.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
Last message (from #PID<0.91.0>): {:open, []}
State: %{closing_fun: nil, ets: nil, fetched: #MapSet<[]>, path: nil, pending: #MapSet<[]>, waiting: %{}}
Client #PID<0.91.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (hex) lib/hex/registry/server.ex:32: Hex.Registry.Server.open/1
    (hex) lib/mix/tasks/hex.info.ex:57: Mix.Tasks.Hex.Info.general/0
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:79: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:63: :elixir_compiler.compile/3

14:08:27.624 [error] GenServer Hex.UpdateChecker terminating
** (UndefinedFunctionError) function :badarg.exception/1 is undefined (module :badarg is not available)
    :badarg.exception([])
    (hex) lib/hex/registry/server.ex:89: Hex.Registry.Server.last_update/0
    (hex) lib/hex/update_checker.ex:110: Hex.UpdateChecker.check_update?/0
    (hex) lib/hex/update_checker.ex:29: Hex.UpdateChecker.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :start_check}
State: %{done: false, from: nil, reply: nil, started: false}
```

* `mix hex.repo list`:
```
Name   URL                  Public key                                          Auth key
hexpm  https://repo.hex.pm  SHA256:O1LOYhHFW4kcrblKAxROaDEzLD8bn1seWbe5tq8TRsk  "some key"
```
## Remarks
* It works correctly for new Elixir project.
* `mix local.hex --force` doesn't help.
* `mix local.rebar --force` doesn't help.
* `mix deps.clean --all` doesn't help.
* Elixir reinstallation doesn't help.
* hex public key seems to be correct.
* It's not connected with any specific dependency.
* Removing `_build` folder doesn't help.

Any ideas what is going on?

## Update: solution

`rm -rf ~/.hex`

**Comment by Skoda091** [comment]
Solution founded: `rm -rf ~/.hex`.
