### ISSUE TITLE
Persistent error when running mix deps.get

### ISSUE THREAD

**Issue by maryolivier** [hexpm/hex#711]
Cannot run `mix deps.get` without getting the following error at the end.

```
User:web user$ elixir -e ":inets_trace.enable(:max, 'trace2.txt', :httpc)" -S mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  accessible 0.2.1
  bamboo 1.2.0
  bamboo_smtp 1.7.0
  bcrypt_elixir 2.0.3
  benchee 1.0.1
  briefly 0.3.0
  bypass 1.0.0
  cabbage 0.3.6
  comeonin 5.1.2
  confex 3.4.0
  credo 1.1.2
  decimal 1.5.0
  ecto_explain 0.1.2
  ecto_job 1.0.0
  ecto_soft_delete 0.2.0
  ex_aws 2.1.1
  ex_aws_s3 2.0.2
  ex_doc 0.21.1
  ex_machina 2.3.0
  ex_rated 1.3.3
  ex_twilio 0.6.1
  excoveralls 0.11.1
  fun_with_flags 1.0.0
  gen_stage 0.14.2
  geo_postgis 2.1.0
  gettext 0.17.0
  hackney 1.15.1
  harmonium 2.1.0
  hound 1.1.0
  inflex 1.10.0
  jason 1.1.2
  kadabra 0.4.4
  licensir 0.4.2
  mix_test_watch 0.9.0
  mogrify 0.7.2
  money 1.4.0
  nimble_csv 0.6.0
  number 1.0.0
  pdf_generator 0.5.7
  phoenix_ecto 3.6.0
  phoenix_html 2.13.3
  phoenix_live_reload 1.2.1
  phoenix_pubsub 1.1.2
  pigeon 1.2.4
  plug_cowboy 2.1.0
  postgrex 0.13.5
  recase 0.6.0
  recon 2.5.0
  retry 0.13.0
  rollbax 0.11.0
  scrivener_ecto 1.3.0
  statix 1.2.1
  sweet_xml 0.6.6
  timex 3.6.1
  typed_struct 0.1.4
  uuid 1.1.8
  vmstats 2.3.1
Upgraded:
  phoenix 1.4.6 => 1.4.8
New:
  base64url 0.0.1
  bunt 0.2.0
  certifi 2.5.1
  combine 0.10.0
  connection 1.0.4
  cowboy 2.6.3
  cowlib 2.7.3
  db_connection 1.1.3
  deep_merge 1.0.0
  earmark 1.3.5
  ecto 2.2.12
  elixir_make 0.6.0
  ex2ms 1.5.0
  file_system 0.2.7
  gen_smtp 0.14.0
  geo 3.2.0
  gherkin 1.6.0
  hpack_erl 0.2.3
  httpoison 1.5.1
  idna 6.0.0
  joken 1.5.0
  jose 1.9.0
  makeup 1.0.0
  makeup_elixir 0.14.0
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  nimble_parsec 0.5.0
  parse_trans 3.3.0
  plug 1.8.3
  plug_crypto 1.0.0
  poison 3.1.0
  poolboy 1.5.2
  ranch 1.7.1
  scrivener 2.7.0
  ssl_verify_fun 1.1.4
  telemetry 0.4.0
  tzdata 1.0.1
  unicode_util_compat 0.4.1
** (FunctionClauseError) no function clause matching in Base.encode16/2    
    
    The following arguments were given to Base.encode16/2:
    
        # 1
        nil
    
        # 2
        [case: :lower]
    
    Attempted function clauses (showing 1 out of 1):
    
        def encode16(data, opts) when is_binary(data)
    
    (elixir) lib/base.ex:271: Base.encode16/2
    (hex) lib/hex/mix.ex:189: anonymous fn/1 in Hex.Mix.to_lock/1
    (elixir) lib/map.ex:210: Map.new_transform/3
    (hex) lib/hex/remote_converger.ex:55: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
```

trace file:
[trace2.txt](https://github.com/hexpm/hex/files/3462845/trace2.txt)

elixir version 1.8.2-otp-21
erlang version 21.3.7

**Comment by maryolivier** [comment]
tried many different things including:
- reinstalling both erlang and elixir
- recloning the repo
- redownloading hex
- removing the _build and mix.lock file
- removing tar files from the .hex/packages/hexpm folder
- `mix deps.unlock --unused`

**Comment by maryolivier** [comment]
solved by deleting the hex directory containing cache.ets from my home directory
