### ISSUE TITLE
mix fails to install dependencies

### ISSUE THREAD

**Issue by aarongraham** [hexpm/hex#744]
We just upgraded to the newest release (0.20.2) using `mix local.hex` and we are now unable to successfully complete a `mix deps.get` run and get the following error when we try. We have not yet tested to see if the install fails for every package or just some. 

```
** (KeyError) key :outer_checksum not found in: %{inner_checksum: "d8bd5404b73273989946e4f4f6d529e5c2088f5fa1ca790b4dbe81f4be408e61", managers: [:rebar], name: "neotoma", repo: "hexpm", version: "1.7.3"}. Did you mean one of:

      * :inner_checksum

    (hex) lib/hex/scm.ex:82: Hex.SCM.lock_status/6
    (hex) lib/hex/scm.ex:363: anonymous fn/2 in Hex.SCM.fetch_from_lock/1
    (elixir) lib/enum.ex:1053: anonymous fn/3 in Enum.flat_map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1964: Enum.flat_map/2
    (hex) lib/hex/scm.ex:342: Hex.SCM.prefetch/1
    (hex) lib/hex/remote_converger.ex:56: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
```

**Comment by ericmj** [comment]
Working on a fix in #744.

**Comment by bryannaegele** [comment]
@ericmj the fix does not appear to be working for some private organization packages. We're seeing consistent failures still with 20.3 (20.1 works). 

Checksums in the lock file do not match what's on hex in some cases.

**Comment by ericmj** [comment]
Can you show the error and your `mix.lock` file?

**Comment by bryannaegele** [comment]
```
** (FunctionClauseError) no function clause matching in Base.encode16/2    
    
    The following arguments were given to Base.encode16/2:
    
        # 1
        nil
    
        # 2
        [case: :lower]
    
    Attempted function clauses (showing 1 out of 1):
    
        def encode16(data, opts) when is_binary(data)
    
    (elixir) lib/base.ex:271: Base.encode16/2
    (hex) lib/hex/mix.ex:194: anonymous fn/1 in Hex.Mix.to_lock/1
    (elixir) lib/map.ex:216: Map.new_transform/3
    (hex) lib/hex/remote_converger.ex:55: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
```

I'll dm you lock info on slack

**Comment by tony612** [comment]
Is there a way to install hex of a specific version? I didn't see the option like `mix local.hex --version`.

**Comment by bryannaegele** [comment]
@tony612 `mix archive.install github hexpm/hex tag v0.20.1`

**Comment by ericmj** [comment]
@tony612 If you are getting any errors please include them here.

**Comment by ericmj** [comment]
Tracking this issue here https://github.com/hexpm/hex/issues/748.
