### ISSUE TITLE
missing `outer_checksum` from downloaded package

### ISSUE THREAD

**Issue by hypno2000** [hexpm/hex#748]
after upgrading from hex 0.20.1 to 0.20.4 and running `mix deps.get` i got:
  ```
  ** (FunctionClauseError) no function clause matching in Base.encode16/2    
    
    The following arguments were given to Base.encode16/2:
    
        # 1
        nil
    
        # 2
        [case: :lower]
    
    Attempted function clauses (showing 1 out of 1):
    
        def encode16(data, opts) when is_binary(data)
    
    (elixir 1.10.0) Base.encode16/2
    (hex 0.20.5-dev) lib/hex/mix.ex:196: anonymous fn/1 in Hex.Mix.to_lock/1
    (elixir 1.10.0) lib/enum.ex:1320: anonymous fn/4 in Enum.into/3
    (elixir 1.10.0) lib/enum.ex:2111: Enum."-into/4-lists^foldl/2-0-"/3
    (elixir 1.10.0) lib/enum.ex:2111: Enum.into/4
    (hex 0.20.5-dev) lib/hex/remote_converger.ex:55: Hex.RemoteConverger.converge/2
    (mix 1.10.0) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.10.0) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix 1.10.0) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.10.0) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
    (mix 1.10.0) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.0) lib/mix/cli.ex:82: Mix.CLI.run_task/2
    (elixir 1.10.0) lib/code.ex:917: Code.require_file/2
  ```

After some debugging found that it is `outer_checksum` that it tires to encode (and is `nil`). The package it is happening with is `coingaming/ex_statsd`.

Added some debugging to `lib/hex/registry/server.ex`:
  ```elixir
  defp write_result({:ok, {code, body, headers}}, repo, package, %{ets: tid})
       when code in 200..299 do
    releases =
      body
      |> :zlib.gunzip()
      |> Hex.Repo.verify(repo)
      |> Hex.Repo.decode_package(repo, package)

    delete_package(repo, package, tid)

    if package == "ex_statsd" do
      IO.inspect({package, releases}, label: "write_result")
    end
```

This revealed that the downloaded package release has the key `outer_checksum` missing.
```
write_result: {"ex_statsd",
 [
   %{
     dependencies: [],
     inner_checksum: <<228, 46, 134, 173, 39, 15, 117, 184, 116, 210, 190, 226,
       203, 140, 218, 2, 178, 156, 119, 234, 98, 211, 235, 244, 126, 59, 125,
       110, 254, 162, 128, 184>>,
     version: "0.5.4"
   }
 ]}
```

**Comment by ericmj** [comment]
It looks like when we rebuilt the registry index files to add the new `:outer_checksum`, all files were not included. I have rebuilt them now, please check if it works now.

/cc @hypno2000 @bryannaegele @tony612

**Comment by bryannaegele** [comment]
Resolved for me @ericmj!

**Comment by tony612** [comment]
It works. Thank you!
