### ISSUE TITLE
hex check failed

### ISSUE THREAD

**Issue by Raymond0331** [hexpm/hex#780]
mix deps.get sometime will occur the following errors :

[15:43:38] ** (exit) exited in: GenServer.call(Hex.UpdateChecker, :check, 60000)
[15:43:38]     ** (EXIT) time out
[15:43:38]     (elixir 1.10.2) lib/gen_server.ex:1023: GenServer.call/3
[15:43:38]     (hex 0.20.5) lib/hex/update_checker.ex:24: Hex.UpdateChecker.check/0
[15:43:38]     (hex 0.20.5) lib/hex/remote_converger.ex:9: Hex.RemoteConverger.post_converge/0
[15:43:38]     (mix 1.10.2) lib/mix/dep/converger.ex:52: Mix.Dep.Converger.converge/4
[15:43:38]     (mix 1.10.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
[15:43:38]     (mix 1.10.2) lib/mix/tasks/deps.get.ex:31: Mix.Tasks.Deps.Get.run/1
[15:43:38]     (mix 1.10.2) lib/mix/task.ex:330: Mix.Task.run_task/3
[15:43:38]     (mix 1.10.2) lib/mix/cli.ex:82: Mix.CLI.run_task/2
[15:43:38]     (mix 1.10.2) lib/mix/cli.ex:82: Mix.CLI.run_task/2

The elixir env. : 
Hex:    0.20.5
Elixir: 1.10.2
OTP:    22.1.8.1

**Comment by ericmj** [comment]
We should catch all timeout errors that can leak to the user and convert to more user friendly errors or warnings.

**Comment by humancalico** [comment]
Hey @ericmj can I work on this? Also is there a mailing list/chat room I can join to ask some of my questions?

**Comment by ericmj** [comment]
@humancalico That would be great.

You can find us on the Elixir slack in the #hex channel or on IRC freenode network in the #elixir-lang channel.

**Comment by humancalico** [comment]
Thanks @ericmj

**Comment by klferreira** [comment]
Are you still working on this issue @humancalico?

**Comment by humancalico** [comment]
@klferreira Unfortunately I got sidetracked and never started working on it :(

**Comment by avillen** [comment]
@ericmj I was taking a look at this issue and I can think about two options:
1. Move the timeouts of the GenServer from the client to the server and handle the timeout with `handle_info` from the GenServer itself. 
2. Catch the error with `try/catch` from the sites of the code where the `Hex.UpdateChecker.check/0` request is done.

WDYT? I'm I right? I was looking for an easy issue to try to contribute :sweat_smile:

**Comment by ericmj** [comment]
> WDYT? I'm I right? I was looking for an easy issue to try to contribute 😅

Yes, I think that's a good solution. Thanks for working on this!

**Comment by avillen** [comment]
@ericmj I have written a proposal, let me know if it makes sense to you. Glad to receive any suggestion :smile:

**Comment by wojtekmach** [comment]
Closing in favour of #896
