### ISSUE TITLE
Hex crashes when re-running the deps.get in a different process

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex#81]
To reproduce go to any project with hex dependencies (like ecto) and run:

```iex
iex(1)> Mix.Task.clear
:ok
iex(2)> Mix.Task.run "run"
** (ArgumentError) argument error
    (stdlib) :ets.lookup(73757, {"poolboy", "1.4.2"})
             lib/hex/registry.ex:110: Hex.Registry.get_deps/2
             lib/hex/remote_converger.ex:58: Hex.RemoteConverger.get_deps/2
       (mix) lib/mix/dep/converger.ex:97: anonymous fn/4 in Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:150: Mix.Dep.Converger.all/8
       (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
       (mix) lib/mix/dep.ex:85: Mix.Dep.loaded/1
       (mix) lib/mix/tasks/deps.check.ex:22: Mix.Tasks.Deps.Check.run/1
```

Either the process that owns the table died or the table does not have the proper visibility. Anyway, it is best to spawn a specific process that owns the table (it could be an agent) and guarantee then it is public.

**Comment by ericmj** [comment]
We should try to start Hex as a proper OTP application with a supervision tree. If we do that it will be easy to fix this issue.

**Comment by josevalim** [comment]
Perfect. Agreed.
