### ISSUE TITLE
[Bug] mix deps.get function :ssl.cipher_suites/1 is undefined or private

### ISSUE THREAD

**Issue by BrendanBall** [hexpm/hex#888]
I'm failing to run `mix deps.get`. It's giving the following error:
```
08:39:19.389 [error] Task #PID<0.159.0> started from Hex.UpdateChecker terminating
** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.4) :ssl.cipher_suites(:openssl)
    (hex 0.20.6) lib/hex/http/ssl.ex:124: Hex.HTTP.SSL.filter_ciphers/1
    (hex 0.20.6) lib/hex/http/ssl.ex:66: Hex.HTTP.SSL.ssl_opts/1
    (hex 0.20.6) lib/hex/http.ex:41: Hex.HTTP.build_http_opts/2
    (hex 0.20.6) lib/hex/http.ex:16: Hex.HTTP.request/5
    (hex 0.20.6) lib/hex/update_checker.ex:31: anonymous fn/0 in Hex.UpdateChecker.handle_cast/2
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<0.54093280/0 in Hex.UpdateChecker.handle_cast/2>
    Args: []
```

This also happens on a new project after adding any random dependency.

Elixir version:
```
➜  elixir --version
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```
OS: Arch Linux

I've checked where this is being called in hex [source](https://github.com/hexpm/hex/blob/2216bd709602b0f544a7e6e90102d14f43724ec6/lib/hex/stdlib.ex#L165) and I've run 

```elixir
➜  test iex
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  Code.ensure_loaded?(:ssl) and function_exported?(:ssl, :cipher_suites, 3)
true
```

I'm not really sure how to debug this further as I'm new to Elixir

This presumably broke after some update as it was working before.

**Comment by wojtekmach** [comment]
Elixir 1.11.3 is not compatible with OTP 24, you need to use 1.11.4 and you should be fine. You can check the compatibility table here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by wojtekmach** [comment]
Actually it's more likely problem with Hex, you can use the latest version by doing: `mix local.hex --force`.

**Comment by BrendanBall** [comment]
ah thanks, `mix local.hex --force` fixed it. Why doesn't hex get updated automatically as part of elixir?
