### ISSUE TITLE
Error when using repo tasks after fresh install

### ISSUE THREAD

**Issue by juanazam** [hexpm/hex#938]
Hello! Thanks for all the hard work on Hex.

Environment Mac OSX Big Sur (11.5.2 )

Elixir 1.13.2
Erlang 24.1.7 (installed using openssl@1.1 via brew)

When running `mix hex.repo list` using the latest hex version, I get the following error:

```
** (FunctionClauseError) no function clause matching in :public_key.pem_decode/1    
    
    The following arguments were given to :public_key.pem_decode/1:
    
        # 1
        :ok
    
    (public_key 1.11) public_key.erl:169: :public_key.pem_decode/1
    (hex 1.0.1) lib/mix/tasks/hex.repo.ex:207: Mix.Tasks.Hex.Repo.show_public_key/1
    (hex 1.0.1) lib/mix/tasks/hex.repo.ex:258: Mix.Tasks.Hex.Repo.show/2
    (mix 1.13.2) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Not sure how can this happen but it seems that here:

https://github.com/hexpm/hex/blob/main/lib/mix/tasks/hex.repo.ex#L168

```
config[:public_key]
```

Contains `:ok`, so when running

https://github.com/hexpm/hex/blob/main/lib/mix/tasks/hex.repo.ex#L207

```
:public_key.pem_decode(public_key)
```

Errors out because `public_key` is `:ok`

Any ideas on why this may be happening?

Thanks!

**Comment by wojtekmach** [comment]
Did you add any organisations or repositories? If something went wrong then, that'd explain it. Check out your `~/.hex/hex.config` if something seems incorrect there. If the problem is there, best to remove the config and re-auth and re-add orgs/repos.

**Comment by juanazam** [comment]
@wojtekmach thanks for you reply, after removing that file `mix hex.repo list` works. But the problem persists while following oban's installation

When running

```
mix hex.repo add oban https://getoban.pro/repo \
    --fetch-public-key $OBAN_KEY_FINGERPRINT \
    --auth-key $OBAN_LICENSE_KEY
```
Results in

```
11:23:05.672 [notice] TLS :client: In state :certify at ssl_handshake.erl:1882 generated CLIENT ALERT: Fatal - Certificate Expired

Downloading public key failed
{:failed_connect, [{:to_address, {'getoban.pro', 443}}, {:inet, [:inet], {:tls_alert, {:certificate_expired, 'TLS client: In state certify at ssl_handshake.erl:1882 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}}]}
```

And  ~/.hex.config to be pupulated with

```
{'$repos',#{<<"oban">> =>
                #{auth_key => <<"XXXXXXXXXXXX">>,
                  fetch_public_key =>
                      <<"XXXXXXXXXXXXXXX">>,
                  public_key => ok,url => <<"https://getoban.pro/repo">>}}}.
```

Basically an entry is added and `public_key` for that entry is `ok`

Not sure if this is a hex issue or an oban issue.

**Comment by wojtekmach** [comment]
> ```erlang
> ...
> fetch_public_key => <<"XXXXXXXXXXXXXXX">>,
> public_key => ok,
> ...
> ```

thank you, this is the problem. If you manually change this to:

```erlang
...
public_key => <<"XXXXXXXXXXXXXXX">>,
...
```

you should be good. Could you try? There's definitely a bug on our end though. Thank you for the report and extra information!

**Comment by juanazam** [comment]
Ran mix hex.info

```
Hex:    1.0.1
Elixir: 1.13.2
OTP:    24.0.3

Built with: Elixir 1.13.0 and OTP 22.3
```

`mix local.hex` doesn't seem to solve the issue

Thanks!

**Comment by juanazam** [comment]
@wojtekmach I see something weird when running `mix hex.info`

```
Ran mix hex.info

Hex:    1.0.1
Elixir: 1.13.2
OTP:    24.0.3

Built with: Elixir 1.13.0 and OTP 22.3
```

The 'Built with' part is not the same as my Elixir and OTP versions listed above, does that make sense?

**Comment by wojtekmach** [comment]
that's not the issue. It just means that the .beam files that ship as part of your hex.ez archive have been compiled against those versions which is completely fine.

**Comment by juanazam** [comment]
@wojtekmach I finally saw the problem, by mistake I added a package via brew that installed erlang as a dependency, and it was shadowing the version installed by `asdf`. closing and *thanks for all your help, I really appreciate it*

**Comment by wojtekmach** [comment]
Awesome, glad it works now!

**Comment by brunolouvem** [comment]
I am getting this same error. 
I also have asdf but only one erlang and elixir version.

My `mix hex.info` is
```
Hex:    2.1.1
Elixir: 1.17.2
OTP:    26.1

Built with: Elixir 1.16.3 and OTP 24.3.4.17
```

When I try add the repo I get this error:

MIX_DEBUG=1 mix hex.repo add oban https://repo.oban.pro/repo --fetch-public-key SHA256:4/OSKi0NRF91QVVXlGAhb/BIMLnK8NHcx/EWs+aIWPc --auth-key $OBAN_LICENSE_KEY

-> Running mix loadconfig (inside MyProject.MixProject)
<- Ran mix loadconfig in 5ms
-> Running mix hex.repo add oban https://repo.oban.pro/repo --fetch-public-key SHA256:4/OSKi0NRF91QVVXlGAhb/BIMLnK8NHcx/EWs+aIWPc --auth-key [redacted] (inside MyProject.MixProject)
Downloading public key failed with code "403"
<- Ran mix hex.repo in 351ms

So after that I can't list repos.

The hex.config file show the public key as :ok and if I remove this and replace by the auth key I get another error like described above:
`** (MatchError) no match of right hand side value: []`
