### ISSUE TITLE
Error with downloading dep (Oban) from different hex repo

### ISSUE THREAD

**Issue by NexPB** [hexpm/hex#978]
```
10:56:28.093 [error] Task #PID<0.264.0> started from :hex_fetcher terminating
** (FunctionClauseError) no function clause matching in Hex.Repo.auth_headers/1
    (hex 2.0.4) lib/hex/repo.ex:238: Hex.Repo.auth_headers(%{auth_key: "**", fetch_public_key: "**", public_key: "**", url: "https://getoban.pro/repo"})
    (hex 2.0.4) lib/hex/repo.ex:175: Hex.Repo.get_package/3
    (hex 2.0.4) lib/hex/registry/server.ex:317: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<18.3350948/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []
```

**Comment by fishtreesugar** [comment]
I am using oban pro and config oban's hex repo according to this docs: https://oban.pro/docs/pro/0.13.0/installation.html#authentication. And I could reproduce this error in hex  since version`2.0.3`

**Comment by vrcca** [comment]
Adding the Oban repo again fixed the issue for me:
```bash
mix hex.repo add oban https://getoban.pro/repo \
    --fetch-public-key $OBAN_PUBLIC_KEY \
    --auth-key $OBAN_AUTH_KEY
```
