### ISSUE TITLE
issue with newly released hex: Could not start Hex.

### ISSUE THREAD

**Issue by sescobb27** [hexpm/hex#981]
Hi there, we are seeing this error in our CI environment on CircleCI on all our services, this wasn't happening on friday and we suspect is something to do with the newly released version

elixir version: `cimg/elixir:1.14`

```
17:13:25.107 [notice] Application hex exited: Hex.Application.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) exited in: GenServer.call(Hex.State, {:get, #Function<0.21698640/1 in Hex.State.fetch!/1>}, 5000)
        ** (EXIT) process attempted to call itself

17:13:25.119 [notice] Application inets exited: :stopped

17:13:25.121 [notice] Application ssl exited: :stopped

17:13:25.121 [notice] Application public_key exited: :stopped

17:13:25.121 [notice] Application asn1 exited: :stopped

17:13:25.121 [notice] Application crypto exited: :stopped
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:calling_self, {GenServer, :call, [Hex.State, {:get, #Function<0.21698640/1 in Hex.State.fetch!/1>}, 5000]}}}}, {Hex.Application, :start, [:normal, []]}}}}
    (hex 2.0.5) lib/hex.ex:5: Hex.start/0
    (mix 1.14.2) lib/mix/hex.ex:59: Mix.Hex.start/0
    (mix 1.14.2) lib/mix/dep/loader.ex:188: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.14.2) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/3
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.14.2) lib/mix/dep/loader.ex:358: Mix.Dep.Loader.mix_children/2
    (mix 1.14.2) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix 1.14.2) lib/mix/dep/converger.ex:80: Mix.Dep.Converger.all/4

Exited with code exit status 1
```

**Comment by jjcarstens** [comment]
FYI - This [got reported on slack](https://elixir-lang.slack.com/archives/C0U07G7FA/p1675703020936569) and @ericmj made a fix in the [ericmj/fix-app-start](https://github.com/hexpm/hex/tree/ericmj/fix-app-start) branch.

I've been told a hotfix release will be out shortly

**Comment by sescobb27** [comment]
ups sorry, i checked #general, #mix but forgot about #hex thank you and sorry
